### ISSUE TITLE
Average L skid

### ISSUE THREAD

**Issue by KDot227** [simplybrin/Invicta-Stealer#2]
no src

**Comment by simplybrin** [comment]
I was curious as to who would leave such an insightful comment, so I decided to navigate to your profile and quickly realized that it's not just the content of character I should judge you by, and that you don't belong in here (as if your profile picture and the title you used wasn't enough).

Even if this did include a source, your tiny brain would vaporize upon seeing it because you don't know how to code in actual programming languages.. are you kidding yourself? you don't even know how to split your code in multiple files and your code is dirtier than Somalian sewers (maybe that's why one of your projects is called "Somalifuscator").

I would see no incentive to make this open source, the only thing it would do is have little kids like you waste two weeks on trying to figure out how to compile this and then start rebranding it as your own and piggybacking off my work. haha, nice try.

**Comment by codeuk** [comment]
You seem to talk too much to people who you act like are beneath you, kid's probably 13. - Waste your time going through my stuff though ;) -

GitHub is (commonly) used for hosting software that others can browse and commit to, of course others will taint it as malicious if you diverge from this; and you haven't done anything to prove otherwise, and from your reply you seem the type to include your special python malware in the builder, which you say your "community" is "actively improv[ing] upon" (lol).

**Comment by KDot227** [comment]
> You seem to talk too much to people who you act like are beneath you, kid's probably 13. - Waste your time going through my stuff though ;) -
> 
> 
> 
> GitHub is (commonly) used for hosting software that others can browse and commit to, of course others will taint it as malicious if you diverge from this; and you haven't done anything to prove otherwise, and from your reply you seem the type to include your special python malware in the builder, which you say your "community" is "actively improv[ing] upon" (lol).

I'm not posting scripts that are dual hooked though but if you want to keep meat riding I'm all for it

**Comment by codeuk** [comment]
I never said you were. I'm was talking about him, not you. Now you've got me thinking that you actually are a retard...
![CharlieBrownGoodGriefGIF](https://github.com/simplybrin/Invicta-Stealer/assets/75194878/1f1b4e36-3938-494c-9bf4-9aff6ba05b8f)

**Comment by KDot227** [comment]
> I was curious as to who would leave such an insightful comment, so I decided to navigate to your profile and quickly realized that it's not just the content of character I should judge you by, and that you don't belong in here (as if your profile picture and the title you used wasn't enough).
> 
> 
> 
> Even if this did include a source, your tiny brain would vaporize upon seeing it because you don't know how to code in actual programming languages.. are you kidding yourself? you don't even know how to split your code in multiple files and your code is dirtier than Somalian sewers (maybe that's why one of your projects is called "Somalifuscator").
> 
> 
> 
> I see no incentive to make this open source, the only thing it would do is have little kids like you waste two weeks on trying to figure out how to compile this and then start rebranding it as your own and piggybacking off my work. haha, nice try, "kid". 
> 
> 
> 
> At least you have self awareness to admit you are a sped, lol!

1.) idk how being a Kendrick fan got to do with anything
2.) read Somalifuscator recode 🤯🤯 also everyone who codes in cpp all say the same things. (Ur a carbon copy of every cpp kid to exist)
3.) GitHub is for "open source development" if you can't honor the simplest request then don't use it lmao
4.) sped.lol is just a funny domain 💀💀💀

**Comment by dxeglow** [comment]
> > I was curious as to who would leave such an insightful comment, so I decided to navigate to your profile and quickly realized that it's not just the content of character I should judge you by, and that you don't belong in here (as if your profile picture and the title you used wasn't enough).
> > Even if this did include a source, your tiny brain would vaporize upon seeing it because you don't know how to code in actual programming languages.. are you kidding yourself? you don't even know how to split your code in multiple files and your code is dirtier than Somalian sewers (maybe that's why one of your projects is called "Somalifuscator").
> > I see no incentive to make this open source, the only thing it would do is have little kids like you waste two weeks on trying to figure out how to compile this and then start rebranding it as your own and piggybacking off my work. haha, nice try, "kid".
> > At least you have self awareness to admit you are a sped, lol!
> 
> 1.) idk how being a Kendrick fan got to do with anything 2.) read Somalifuscator recode 🤯🤯 also everyone who codes in cpp all say the same things. (Ur a carbon copy of every cpp kid to exist) 3.) GitHub is for "open source development" if you can't honor the simplest request then don't use it lmao 4.) sped.lol is just a funny domain 💀💀💀


1.) No one asked for your opinion on this matter.
2.) No one will study the code of your obfuscator in Python for the dead batch language (seriously, no one codes in it).
3.) The author's source code is their property, which means they have the right not to publish it and only release the builder.
4.) No one is interested in why you chose this particular domain.

**Comment by KDot227** [comment]
> > 1.) idk how being a Kendrick fan got to do with anything 2.) read Somalifuscator recode 🤯🤯 also everyone who codes in cpp all say the same things. (Ur a carbon copy of every cpp kid to exist) 3.) GitHub is for "open source development" if you can't honor the simplest request then don't use it lmao 4.) sped.lol is just a funny domain 💀💀💀
> 
> 
> 
> 
> 
> 1.) No one asked for your opinion on this matter.
> 
> 2.) No one will study the code of your obfuscator in Python for the dead batch language (seriously, no one codes in it).
> 
> 3.) The author's source code is their property, which means they have the right not to publish it and only release the builder.
> 
> 4.) No one is interested in why you chose this particular domain.

1.) neither did they ask you
2.) still the best in the world
3.) GitHub is exclusively meant for open source code. This is most likely malware which is why they won't post the source. (very common for people to do this especially when they're posting malware) Meaning this is breaking TOS in 2 different ways lol I'm just trying to help people stay safe and not downloading dumb dual hooked malware that probably doesn't even work.
4.) idk if the person I responded to even kept their comment but I wasn't talking to the author
